account/urls.py
from django.contrib import admin
from django.urls import path,include, re_path
from django.contrib.auth.views import (
    LogoutView,
    # PasswordResetView,
    # PasswordResetDoneView,
    # PasswordResetConfirmView,
    # PasswordResetCompleteView
) 
from . import views 
# from custom_admin import views as custom_admin_view

app_name = "account"

urlpatterns = [
    path('login/', views.CustomLoginView.as_view(), name="login"),
    path("logout/", LogoutView.as_view(template_name="account/logout.html"), name="logout"),
    path("signup/", views.SignUpView.as_view(), name="signup"),
    path("dashboard/", views.dashboard, name="dashboard"),
    path("dashboard/profile/create", views.CompanyProfileCreateView.as_view(), name="profile_create")
    # path('dashboard/track/<int:pk>/',views.DashboardTrackDetailView.as_view(), name="track_detail"),
    # # path('dashboard/track/<int:pk>/master',views.master, name="track_master"),
    # re_path('dashboard/track/(?P<username>\w+)/download/$',views.download_mastered_files, name="track_mastered_download"),
    # path('dashboard/payment-customer-info',views.payment_customer_info,name='payment_customer_info'),
    # path('dashboard/support-ticket/add', custom_admin_view.SupportTicketCreateView.as_view(), name="support_ticket_add"),
    # path('dashboard/support-ticket/list', custom_admin_view.SupportTicketListView.as_view(),name="list_ticket"),
    # path('dashboard/support-ticket/<int:pk>/detail', custom_admin_view.SupportDetailView.as_view(),name="detail_ticket"),
    # path('dashboard/mastered/tracks', views.MasteredTracksListView.as_view(),name="mastered_tracks"),

    # path('dashboard/track/<int:pk>/edit', views.MasteringEditTrackView.as_view(), name="track_edit"),
    # path("dashboard/track/<int:pk>/delete", views.MasteringDeleteTrackView.as_view(), name="delete_edit")
]

custom_admin/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views 

app_name ="custom_admin"

urlpatterns = [
    path('login', views.AdminLoginView.as_view(), name="admin_login"),
    path('dashboard', views.Dashboard.as_view(),name="admin_dashboard"),
    path("dashboard/<int:pk>/profile", views.CompanyProfileDetailView.as_view(), name="profile_detail"),
    path("dashboard/profile/create", views.CompanyProfileCreateView.as_view(), name="profile_create"),

]

mysite/urls.py
from django.contrib import admin
from django.urls import path, include 
from django.contrib.auth.views import (
    PasswordResetView,
    PasswordResetDoneView,
    PasswordResetConfirmView,
    PasswordResetCompleteView
) 
from account.forms import (
    PasswordChangeNewForm, PasswordResetNewForm,SetPasswordNewForm
)
from . import views 


handler400 = 'utils.views.page_not_found'
handler500 = 'utils.views.server_error'

urlpatterns = [
    path('dev/admin/', admin.site.urls),

    path('', include('account.urls')),
    path('', views.HomeView.as_view(), name="home"),
    path('about', views.AboutView.as_view(), name="about"),
    path('contact', views.ContactView.as_view(), name="contact"),
    path('service', views.ServiceView.as_view(), name="service"),
    path('password_reset/',PasswordResetView.as_view(template_name="account/password_reset_form.html", form_class=PasswordResetNewForm), name="password_reset"),
    path('password_reset/done/',PasswordResetDoneView.as_view(template_name="account/password_reset_email_done.html"), name="password_reset_done"),
    path("reset/<uidb64>/<token>/",PasswordResetConfirmView.as_view(template_name="account/password_reset_confirm.html", form_class=SetPasswordNewForm), name="password_reset_confirm"),
    path("reset/done/", PasswordResetCompleteView.as_view(template_name="account/password_reset_done.html"), name="password_reset_complete"),
    path('admin/', include('custom_admin.urls')),
]

from django.conf.urls.static import static
from django.conf import settings


urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/includes/sidebaradmin.html
{% load static %}
<aside class="main-sidebar sidebar-dark-primary elevation-4">
    <!-- Brand Logo -->
    <a href="#" class="brand-link">
      <img src="{% static 'dashboard/img/AdminLTELogo.png' %}" alt="AdminLTE Logo" class="brand-image img-circle elevation-3"
           style="opacity: .8">
      <span class="brand-text font-weight-light">Admin3</span>
    </a>

    <!-- Sidebar -->
    <div class="sidebar">
      <!-- Sidebar user panel (optional) -->
      <div class="user-panel mt-3 pb-3 mb-3 d-flex">
        {% if request.user.profile_admin %}
        <div class="image">
          <img src="{{request.user.profile_admin.profile_pic.url}}" class="img-circle elevation-2" alt="User Image">
        </div>
        {% endif %}

        <div class="info">
          {% if request.user.profile_admin %}
          <a href="#" class="d-block">{{request.user.profile_admin.fullname}}</a>
          {% endif %}
        </div>

      </div>

      <!-- Sidebar Menu -->
      <nav class="mt-2">
        <ul class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu" data-accordion="false">
          <!-- Add icons to the links using the .nav-icon class
               with font-awesome or any other icon font library -->
               <li class="nav-item">
                <a href="{% url 'home' %}" class="nav-link">
                  <i class="nav-icon fas fa-th"></i>
                  <p>
                    Home
                    <!-- <span class="right badge badge-danger">New</span> -->
                  </p>
                </a>
              </li>
              
          <li class="nav-item">
            <a href="{% url 'custom_admin:admin_dashboard'   %}" class="nav-link">
              <i class="nav-icon fas fa-th"></i>
              <p>
                Dashboard
                <!-- <span class="right badge badge-danger">New</span> -->
              </p>
            </a>
          </li>
          {% if request.user.profile_admin %}
          <li class="nav-item">
            <a href="#" class="nav-link">
              <i class="nav-icon fas fa-th"></i>
              <p>
               Edit Profile
                <!-- <span class="right badge badge-danger">New</span> -->
              </p>
            </a>
          </li>
          {% else %}
          <li class="nav-item">
            <a href="{% url 'custom_admin:profile_create'   %}" class="nav-link">
              <i class="nav-icon fas fa-th"></i>
              <p>
               Add Profile
                <!-- <span class="right badge badge-danger">New</span> -->
              </p>
            </a>
          </li>
          {% endif %}
          <li class="nav-item">
            <a href="{% url 'account:logout'   %}" class="nav-link">
              <i class="nav-icon fas fa-user"></i>
              <p>
               Logout
                <!-- <span class="right badge badge-danger">New</span> -->
              </p>
            </a>
          </li>
          {% if request.user.profile_admin %}

          <li class="nav-item has-treeview">
            <a href="{% url 'custom_admin:profile_detail' request.user.profile_admin.id %}" class="nav-link">
              <i class="nav-icon fas fa-user"></i>
              <p>
                Profile
                <i class="fas fa-angle-left right"></i>
                <span class="badge badge-info right">6</span>
              </p>
            </a>
            <!-- <ul class="nav nav-treeview">
              <li class="nav-item">
                <a href="pages/layout/top-nav.html" class="nav-link">
                  <i class="far fa-circle nav-icon"></i>
                  <p>Top Navigation</p>
                </a>
              </li>
              <li class="nav-item">
                <a href="pages/layout/top-nav-sidebar.html" class="nav-link">
                  <i class="far fa-circle nav-icon"></i>
                  <p>Top Navigation + Sidebar</p>
                </a>
              </li>
              <li class="nav-item">
                <a href="pages/layout/boxed.html" class="nav-link">
                  <i class="far fa-circle nav-icon"></i>
                  <p>Boxed</p>
                </a>
              </li>
              <li class="nav-item">
                <a href="pages/layout/fixed-sidebar.html" class="nav-link">
                  <i class="far fa-circle nav-icon"></i>
                  <p>Fixed Sidebar</p>
                </a>
              </li>
              <li class="nav-item">
                <a href="pages/layout/fixed-topnav.html" class="nav-link">
                  <i class="far fa-circle nav-icon"></i>
                  <p>Fixed Navbar</p>
                </a>
              </li>
              <li class="nav-item">
                <a href="pages/layout/fixed-footer.html" class="nav-link">
                  <i class="far fa-circle nav-icon"></i>
                  <p>Fixed Footer</p>
                </a>
              </li>
              <li class="nav-item">
                <a href="pages/layout/collapsed-sidebar.html" class="nav-link">
                  <i class="far fa-circle nav-icon"></i>
                  <p>Collapsed Sidebar</p>
                </a>
              </li>
            </ul> -->
          </li>
          {% endif %}
        </ul>
      </nav>
      <!-- /.sidebar-menu -->
    </div>
    <!-- /.sidebar -->
  </aside>

templates/includes/sidebaruser.html
{% load static %}
<aside class="main-sidebar sidebar-dark-primary elevation-4">
    <!-- Brand Logo -->
    <a href="#" class="brand-link">
      <img src="{% static 'dashboard/img/AdminLTELogo.png' %}" alt="AdminLTE Logo" class="brand-image img-circle elevation-3"
           style="opacity: .8">
      <span class="brand-text font-weight-light">Admin3</span>
    </a>

    <!-- Sidebar -->
    <!-- Sidebar -->
    <div class="sidebar">
      <!-- Sidebar user panel (optional) -->
      <div class="user-panel mt-3 pb-3 mb-3 d-flex">
        {% if request.user.profile_admin %}
        <div class="image">
          <img src="{{request.user.profile_admin.profile_pic.url}}" class="img-circle elevation-2" alt="User Image">
        </div>
        {% endif %}

        <div class="info">
          {% if request.user.profile_admin %}
          <a href="#" class="d-block">{{request.user.profile_admin.fullname}}</a>
          {% endif %}
        </div>

      </div>

      <!-- Sidebar Menu -->
      <nav class="mt-2">
        <ul class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu" data-accordion="false">
          <!-- Add icons to the links using the .nav-icon class
               with font-awesome or any other icon font library -->
               <li class="nav-item">
                <a href="{% url 'home' %}" class="nav-link">
                  <i class="nav-icon fas fa-th"></i>
                  <p>
                    Home
                    <!-- <span class="right badge badge-danger">New</span> -->
                  </p>
                </a>
              </li>
              
          <li class="nav-item">
            <a href="{% url 'account:dashboard'   %}" class="nav-link">
              <i class="nav-icon fas fa-th"></i>
              <p>
                Dashboard
                <!-- <span class="right badge badge-danger">New</span> -->
              </p>
            </a>
          </li>
          {% if request.user.profile_user %}
          <li class="nav-item">
            <a href="#" class="nav-link">
              <i class="nav-icon fas fa-th"></i>
              <p>
               Edit Profile
                <!-- <span class="right badge badge-danger">New</span> -->
              </p>
            </a>
          </li>
          {% else %}
          <li class="nav-item">
            <a href="{% url 'account:profile_create'   %}" class="nav-link">
              <i class="nav-icon fas fa-th"></i>
              <p>
               Add Profile
                <!-- <span class="right badge badge-danger">New</span> -->
              </p>
            </a>
          </li>
          {% endif %}
          <li class="nav-item">
            <a href="{% url 'account:logout'   %}" class="nav-link">
              <i class="nav-icon fas fa-user"></i>
              <p>
               Logout
                <!-- <span class="right badge badge-danger">New</span> -->
              </p>
            </a>
          </li>
        </ul>
      </nav>
      <!-- /.sidebar-menu -->
    </div>
    <!-- /.sidebar -->
  </aside>