account/urls.py
from django.contrib import admin
from django.urls import path,include, re_path
from django.contrib.auth.views import (
    LogoutView,
    # PasswordResetView,
    # PasswordResetDoneView,
    # PasswordResetConfirmView,
    # PasswordResetCompleteView
) 
from . import views 
# from custom_admin import views as custom_admin_view

app_name = "account"

urlpatterns = [
    path('login/', views.CustomLoginView.as_view(), name="login"),
    path("logout/", LogoutView.as_view(template_name="account/logout.html"), name="logout"),
    path("signup/", views.SignUpView.as_view(), name="signup"),
    path("dashboard/", views.dashboard, name="dashboard"),
    path("dashboard/profile/create", views.CompanyProfileCreateView.as_view(), name="profile_create")
    # path('dashboard/track/<int:pk>/',views.DashboardTrackDetailView.as_view(), name="track_detail"),
    # # path('dashboard/track/<int:pk>/master',views.master, name="track_master"),
    # re_path('dashboard/track/(?P<username>\w+)/download/$',views.download_mastered_files, name="track_mastered_download"),
    # path('dashboard/payment-customer-info',views.payment_customer_info,name='payment_customer_info'),
    # path('dashboard/support-ticket/add', custom_admin_view.SupportTicketCreateView.as_view(), name="support_ticket_add"),
    # path('dashboard/support-ticket/list', custom_admin_view.SupportTicketListView.as_view(),name="list_ticket"),
    # path('dashboard/support-ticket/<int:pk>/detail', custom_admin_view.SupportDetailView.as_view(),name="detail_ticket"),
    # path('dashboard/mastered/tracks', views.MasteredTracksListView.as_view(),name="mastered_tracks"),

    # path('dashboard/track/<int:pk>/edit', views.MasteringEditTrackView.as_view(), name="track_edit"),
    # path("dashboard/track/<int:pk>/delete", views.MasteringDeleteTrackView.as_view(), name="delete_edit")
]

custom_admin/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views 

app_name ="custom_admin"

urlpatterns = [
    path('login', views.AdminLoginView.as_view(), name="admin_login"),
    path('dashboard', views.Dashboard.as_view(),name="admin_dashboard"),
    path("dashboard/<int:pk>/profile", views.CompanyProfileDetailView.as_view(), name="profile_detail"),
    path("dashboard/profile/create", views.CompanyProfileCreateView.as_view(), name="profile_create"),

]

mysite/urls.py
from django.contrib import admin
from django.urls import path, include 
from django.contrib.auth.views import (
    PasswordResetView,
    PasswordResetDoneView,
    PasswordResetConfirmView,
    PasswordResetCompleteView
) 
from account.forms import (
    PasswordChangeNewForm, PasswordResetNewForm,SetPasswordNewForm
)
from . import views 


handler400 = 'utils.views.page_not_found'
handler500 = 'utils.views.server_error'

urlpatterns = [
    path('dev/admin/', admin.site.urls),

    path('', include('account.urls')),
    path('', views.HomeView.as_view(), name="home"),
    path('about', views.AboutView.as_view(), name="about"),
    path('contact', views.ContactView.as_view(), name="contact"),
    path('service', views.ServiceView.as_view(), name="service"),
    path('password_reset/',PasswordResetView.as_view(template_name="account/password_reset_form.html", form_class=PasswordResetNewForm), name="password_reset"),
    path('password_reset/done/',PasswordResetDoneView.as_view(template_name="account/password_reset_email_done.html"), name="password_reset_done"),
    path("reset/<uidb64>/<token>/",PasswordResetConfirmView.as_view(template_name="account/password_reset_confirm.html", form_class=SetPasswordNewForm), name="password_reset_confirm"),
    path("reset/done/", PasswordResetCompleteView.as_view(template_name="account/password_reset_done.html"), name="password_reset_complete"),
    path('admin/', include('custom_admin.urls')),
]

from django.conf.urls.static import static
from django.conf import settings


urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/base.html
<!doctype html>
{% load static %}
<html class="no-js" lang="zxx">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="x-ua-compatible" content="ie=edge">
        <title>SociaRiot</title>
        <meta name="description" content="">
        <meta name="viewport" content="width=device-width, initial-scale=1">

        <link rel="manifest" href="site.webmanifest">
		<link rel="shortcut icon" type="image/x-icon" href="{% static 'assets/img/favicon.ico' %}">

		<!-- CSS here -->
            <link rel="stylesheet" href="{% static 'assets/css/bootstrap.min.css' %}">
            <link rel="stylesheet" href="{% static 'assets/css/owl.carousel.min.css' %}">
            <link rel="stylesheet" href="{% static 'assets/css/flaticon.css' %}">
            <link rel="stylesheet" href="{% static 'assets/css/slicknav.css' %}">
            <link rel="stylesheet" href="{% static 'assets/css/animate.min.css' %}">
            <link rel="stylesheet" href="{% static 'assets/css/magnific-popup.css' %}">
            <link rel="stylesheet" href="{% static 'assets/css/fontawesome-all.min.css' %}">
            <link rel="stylesheet" href="{% static 'assets/css/themify-icons.css' %}">
            <link rel="stylesheet" href="{% static 'assets/css/slick.css' %}">
            <link rel="stylesheet" href="{% static 'assets/css/nice-select.css' %}">
            <link rel="stylesheet" href="{% static 'assets/css/style.css' %}">
   </head>
   <body>
    <!-- Preloader Start -->
    <div id="preloader-active">
        <div class="preloader d-flex align-items-center justify-content-center">
            <div class="preloader-inner position-relative">
                <div class="preloader-circle"></div>
                <div class="preloader-img pere-text">
                    <img src="assets/img/logo/logo.png" alt="">
                </div>
            </div>
        </div>
    </div>
    <!-- Preloader Start -->

<header>
    <!-- Header Start -->
   <div class="header-area header-transparrent ">
        <div class="main-header header-sticky">
            <div class="container">
                <div class="row align-items-center">
                    <!-- Logo -->
                    <div class="col-xl-2 col-lg-2 col-md-1">
                        <div class="logo">
                            <a href="{% url 'home'%}"><img src="{% static 'assets/img/logo/logo.png' %}" alt=""></a>
                        </div>
                    </div>
                    <div class="col-xl-8 col-lg-8 col-md-8">
                        <!-- Main-menu -->
                        <div class="main-menu f-right d-none d-lg-block">
                            <nav> 
                                <ul id="navigation">    
                                    <li><a href="{% url 'home' %}"> Home</a></li>
                                    <li><a href="{% url 'about' %}">About Us</a></li>
                                    <li><a href="{% url 'service'%}">Services</a></li>
                                    <li><a href="{% url 'contact'%}">Contact</a></li>
                                    {% if request.user.is_authenticated %}
                                        {% if request.user.is_superuser %}
                                        
                                        <li><a href="{% url 'custom_admin:admin_dashboard' %}">Dashboard</a></li>

                                        {% else %}
                                        <li><a href="{% url 'account:dashboard' %}">Dashboard</a></li>
                                        {% endif %}
                                    <li><a href="{% url 'account:logout' %}">Logout</a></li>
                                    {% else %}
                                    <li><a href="{% url 'account:login' %}">Login</a></li>
                                    {% endif %}

                                    <!-- <li><a href="{% url 'home'%}">Blog</a>
                                        <ul class="submenu">
                                            <li><a href="blog.html">Blog</a></li>
                                            <li><a href="single-blog.html">Blog Details</a></li>
                                        </ul>
                                    </li>
                                    <li><a href="#">Pages</a>
                                        <ul class="submenu">
                                            <li><a href="elements.html">Element</a></li>
                                        </ul>
                                    </li> -->
                                </ul>
                            </nav>
                        </div>
                    </div>             
                    <div class="col-xl-2 col-lg-2 col-md-3">
                        <div class="header-right-btn f-right d-none d-lg-block">
                            <a href="#" class="btn header-btn">Contact Us</a>
                        </div>
                    </div>
                    <!-- Mobile Menu -->
                    <div class="col-12">
                        <div class="mobile_menu d-block d-lg-none"></div>
                    </div>
                </div>
            </div>
        </div>
   </div>
    <!-- Header End -->
</header>

{% block content %}
{% endblock %}
<footer>

    <!-- Footer Start-->
   <div class="footer-main" data-background="assets/img/shape/footer_bg.png">
     <div class="footer-area footer-padding">
         <div class="container">
             <div class="row d-flex justify-content-between">
                 <div class="col-lg-3 col-md-4 col-sm-8">
                    <div class="single-footer-caption mb-50">
                      <div class="single-footer-caption mb-30">
                           <!-- logo -->
                          <div class="footer-logo">
                              <a href="index.html"><img src="assets/img/logo/logo2_footer.png" alt=""></a>
                          </div>
                          <div class="footer-tittle">
                              <div class="footer-pera">
                                  <p class="info1">221B Baker Street, P.O Box 353 Park <br> Road, USA - 215431</p>
                                  <p class="info2">info@yourdomain.com</p>
                             </div>
                          </div>
                          <div class="footer-social">
                             <a href="#"><i class="fab fa-facebook-f"></i></a>
                             <a href="#"><i class="fab fa-twitter"></i></a>
                             <a href="#"><i class="fas fa-globe"></i></a>
                             <a href="#"><i class="fab fa-behance"></i></a>
                         </div>
                      </div>
                    </div>
                 </div>
                 <div class="col-lg-2 col-md-4 col-sm-5">
                     <div class="single-footer-caption mb-50">
                         <div class="footer-tittle">
                             <h4>Quick Links</h4>
                             <ul>
                                 <li><a href="about.html">About</a></li>
                                 <li><a href="about.html">Features</a></li>
                                 <li><a href="single-blog.html">Pricing</a></li>
                                 <li><a href="blog.html">Blog</a></li>
                                 <li><a href="contact.html">Contact</a></li>
                             </ul>
                         </div>
                     </div>
                 </div>
                 <div class="col-lg-2 col-md-4 col-sm-7">
                     <div class="single-footer-caption mb-50">
                         <div class="footer-tittle">
                             <h4>Support</h4>
                             <ul>
                                 <li><a href="#">Privacy Policy</a></li>
                                 <li><a href="#">Terms & Conditions</a></li>
                                 <li><a href="#"> Sitemap</a></li>
                                 <li><a href="#">FAQs</a></li>
                                 <li><a href="#">Report a bugb</a></li>
                             </ul>
                         </div>
                     </div>
                 </div>
                 <div class="col-lg-3 col-md-4 col-sm-5">
                     <div class="single-footer-caption mb-50">
                         <div class="footer-tittle">
                             <h4>Core Features</h4>
                             <ul>
                              <li><a href="#">Email Marketing</a></li>
                              <li><a href="#"> Offline SEO</a></li>
                              <li><a href="#">Social Media Marketing</a></li>
                              <li><a href="#">Lead Generation</a></li>
                              <li><a href="#"> 24/7 Support</a></li>
                          </ul>
                         </div>
                     </div>
                 </div>
             </div>
         </div>
     </div>
     <!-- footer-bottom aera -->
     <div class="footer-bottom-area footer-bg">
         <div class="container">
             <div class="footer-border">
                  <div class="row d-flex align-items-center">
                      <div class="col-xl-12 ">
                          <div class="footer-copy-right text-center">
                              <p><!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
Copyright &copy;<script>document.write(new Date().getFullYear());</script> All rights reserved | This template is made with <i class="ti-heart" aria-hidden="true"></i> by <a href="https://colorlib.com" target="_blank">Colorlib</a>
<!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. --></p>
                          </div>
                      </div>
                  </div>
             </div>
         </div>
     </div>
   </div>
    <!-- Footer End-->

</footer>

 <!-- JS here -->
 
     <!-- All JS Custom Plugins Link Here here -->
     <script src="{% static 'assets/js/vendor/modernizr-3.5.0.min.js' %}"></script>
     <!-- Jquery, Popper, Bootstrap -->
     <script src="{% static 'assets/js/vendor/jquery-1.12.4.min.js' %}"></script>
     <script src="{% static 'assets/js/popper.min.js' %}"></script>
     <script src="{% static 'assets/js/bootstrap.min.js' %}"></script>
     <!-- Jquery Mobile Menu -->
     <script src="{% static 'assets/js/jquery.slicknav.min.js' %}"></script>

     <!-- Jquery Slick , Owl-Carousel Plugins -->
     <script src="{% static 'assets/js/owl.carousel.min.js' %}"></script>
     <script src="{% static 'assets/js/slick.min.js' %}"></script>
     <!-- Date Picker -->
     <script src="{% static 'assets/js/gijgo.min.js' %}"></script>
     <!-- One Page, Animated-HeadLin -->
     <script src="{% static 'assets/js/wow.min.js' %}"></script>
     <script src="{% static 'assets/js/animated.headline.js' %}"></script>
     <script src="{% static 'assets/js/jquery.magnific-popup.js' %}"></script>

     <!-- Scrollup, nice-select, sticky -->
     <script src="{% static 'assets/js/jquery.scrollUp.min.js' %}"></script>
     <script src="{% static 'assets/js/jquery.nice-select.min.js '%}'"></script>
     <script src="{% static 'assets/js/jquery.sticky.js' %}"></script>
     
     <!-- contact js -->
     <script src="{% static 'assets/js/contact.js' %}"></script>
     <script src="{% static 'assets/js/jquery.form.js' %}"></script>
     <script src="{% static 'assets/js/jquery.validate.min.js' %}"></script>
     <script src="{% static 'assets/js/mail-script.js' %}"></script>
     <script src="{% static 'assets/js/jquery.ajaxchimp.min.js' %}"></script>
     
     <!-- Jquery Plugins, main Jquery -->	
     <script src="{% static 'assets/js/plugins.js' %}"></script>
     <script src="{% static 'assets/js/main.js' %}"></script>
     
 </body>
</html>